POST http://localhost:3000/api/patients/
Content-Type: application/json

{
    "name": "John Mckenley",
    "dateOfBirth": "1988-10-07",
    "ssn": "090286-122X",
    "gender": "male",
    "occupation": "Rovaniemi"
  }