POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvcmlzMTIzIiwiaWQiOiI2NzY1NWE1MTljNmFmMDgyODkyMWFjODEiLCJpYXQiOjE3MzQ3MDM1NDB9.BCFsUDAVc83UIc4xpNJ1rH7Hmc1tx4xgKD_ezczVbjg

{
  "title": "this is new blog for boris",
  "author": "New author",
  "url": "http://test.com",
  "likes": 44,
  "userId": "675ed514cda8d9c9b3a1592f"
}