POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvcmlzMTIzIiwiaWQiOiI2NzY1NWE1MTljNmFmMDgyODkyMWFjODEiLCJpYXQiOjE3MzQ2OTg3NTh9.iPCyP-j-A52iALtFpiKVRDJcaiZWaq2JLBnys7hKNp0

{
  "title": "this is new blog7",
  "author": "New author",
  "url": "http://test.com",
  "likes": 44,
  "userId": "675ed514cda8d9c9b3a1592f"
}